package MyBlog.Model;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.ID
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.TITTLE
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private String tittle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.DISCRIPTION
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private String discription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.GMT_CREATE
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.GMT_MODIFIED
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.CREATOR
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.COMMENT_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.VIEW_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.LIKE_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.TAG
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.ID
     *
     * @return the value of ARTICLE.ID
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.ID
     *
     * @param id the value for ARTICLE.ID
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.TITTLE
     *
     * @return the value of ARTICLE.TITTLE
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public String getTittle() {
        return tittle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.TITTLE
     *
     * @param tittle the value for ARTICLE.TITTLE
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setTittle(String tittle) {
        this.tittle = tittle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.DISCRIPTION
     *
     * @return the value of ARTICLE.DISCRIPTION
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.DISCRIPTION
     *
     * @param discription the value for ARTICLE.DISCRIPTION
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setDiscription(String discription) {
        this.discription = discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.GMT_CREATE
     *
     * @return the value of ARTICLE.GMT_CREATE
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.GMT_CREATE
     *
     * @param gmtCreate the value for ARTICLE.GMT_CREATE
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.GMT_MODIFIED
     *
     * @return the value of ARTICLE.GMT_MODIFIED
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.GMT_MODIFIED
     *
     * @param gmtModified the value for ARTICLE.GMT_MODIFIED
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.CREATOR
     *
     * @return the value of ARTICLE.CREATOR
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.CREATOR
     *
     * @param creator the value for ARTICLE.CREATOR
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.COMMENT_COUNT
     *
     * @return the value of ARTICLE.COMMENT_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.COMMENT_COUNT
     *
     * @param commentCount the value for ARTICLE.COMMENT_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.VIEW_COUNT
     *
     * @return the value of ARTICLE.VIEW_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.VIEW_COUNT
     *
     * @param viewCount the value for ARTICLE.VIEW_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.LIKE_COUNT
     *
     * @return the value of ARTICLE.LIKE_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.LIKE_COUNT
     *
     * @param likeCount the value for ARTICLE.LIKE_COUNT
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.TAG
     *
     * @return the value of ARTICLE.TAG
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.TAG
     *
     * @param tag the value for ARTICLE.TAG
     *
     * @mbg.generated Tue Oct 01 04:16:51 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}