CREATE TABLE USER
(
  ID           INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ACCOUNTID    VARCHAR(50),
  NAME         VARCHAR(50),
  TOKEN        VARCHAR(100),
  GMT_CREATE   BIGINT,
  GMT_MODIFIED BIGINT
)